namespace GPG.Multiplayer.Client.Vaulting.Applications
{
    using DevExpress.Utils;
    using DevExpress.XtraEditors.Controls;
    using GPG.Multiplayer.Client;
    using GPG.Multiplayer.Client.Controls;
    using GPG.Multiplayer.Client.Games;
    using GPG.Multiplayer.Quazal;
    using GPG.Multiplayer.UI.Controls;
    using GPG.UI;
    using GPG.UI.Controls;
    using System;
    using System.ComponentModel;
    using System.Drawing;
    using System.Drawing.Drawing2D;
    using System.Windows.Forms;

    public class DlgGameVersionManager : DlgBase
    {
        private GPGBorderPanel bpGames;
        private GPGBorderPanel bpModify;
        private IContainer components = null;
        private GPGLabel gpgLabel1;
        private GPGLabel gpgLabel10;
        private GPGLabel gpgLabel11;
        private GPGLabel gpgLabel2;
        private GPGLabel gpgLabel3;
        private GPGLabel gpgLabel4;
        private GPGLabel gpgLabel5;
        private GPGLabel gpgLabel6;
        private GPGLabel gpgLabel7;
        private GPGLabel gpgLabel8;
        private GPGLabel gpgLabel9;
        private ListBox lbGames;
        private bool mAddMode = false;
        public SkinButton sbAdd;
        public SkinButton sbCancel;
        public SkinButton sbModify;
        public SkinButton sbSaveChanges;
        private GPGTextBox tbCurrentBuild;
        private GPGTextBox tbDescription;
        private GPGTextBox tbExeName;
        private GPGTextBox tbForcedCommandLineArgs;
        private GPGTextBox tbIconLabel;
        private GPGTextBox tbInstallDirectory;
        private GPGTextArea tbLongDescription;
        private GPGTextBox tbPatcherAppUrl;
        private GPGTextBox tbPatchUrl;
        private GPGTextBox tbRelativeAppDirectory;
        private GPGTextBox tbRelativeVersionFile;

        public DlgGameVersionManager()
        {
            this.InitializeComponent();
            this.RefreshGamesList();
            this.lbGames.Click += new EventHandler(this.lbGames_Click);
            this.sbAdd.Click += new EventHandler(this.sbAdd_Click);
            this.sbModify.Click += new EventHandler(this.sbModify_Click);
            this.sbCancel.Click += new EventHandler(this.sbCancel_Click);
            this.sbSaveChanges.Click += new EventHandler(this.sbSaveChanges_Click);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.lbGames = new ListBox();
            this.bpModify = new GPGBorderPanel();
            this.tbLongDescription = new GPGTextArea();
            this.gpgLabel11 = new GPGLabel();
            this.tbInstallDirectory = new GPGTextBox();
            this.gpgLabel10 = new GPGLabel();
            this.tbPatchUrl = new GPGTextBox();
            this.gpgLabel9 = new GPGLabel();
            this.tbPatcherAppUrl = new GPGTextBox();
            this.gpgLabel8 = new GPGLabel();
            this.tbIconLabel = new GPGTextBox();
            this.gpgLabel7 = new GPGLabel();
            this.tbForcedCommandLineArgs = new GPGTextBox();
            this.gpgLabel6 = new GPGLabel();
            this.tbRelativeAppDirectory = new GPGTextBox();
            this.gpgLabel5 = new GPGLabel();
            this.tbRelativeVersionFile = new GPGTextBox();
            this.gpgLabel4 = new GPGLabel();
            this.tbCurrentBuild = new GPGTextBox();
            this.gpgLabel1 = new GPGLabel();
            this.gpgLabel2 = new GPGLabel();
            this.tbDescription = new GPGTextBox();
            this.tbExeName = new GPGTextBox();
            this.gpgLabel3 = new GPGLabel();
            this.sbAdd = new SkinButton();
            this.sbModify = new SkinButton();
            this.sbCancel = new SkinButton();
            this.sbSaveChanges = new SkinButton();
            this.bpGames = new GPGBorderPanel();
            ((ISupportInitialize) base.pbBottom).BeginInit();
            this.bpModify.SuspendLayout();
            this.tbLongDescription.Properties.BeginInit();
            this.tbInstallDirectory.Properties.BeginInit();
            this.tbPatchUrl.Properties.BeginInit();
            this.tbPatcherAppUrl.Properties.BeginInit();
            this.tbIconLabel.Properties.BeginInit();
            this.tbForcedCommandLineArgs.Properties.BeginInit();
            this.tbRelativeAppDirectory.Properties.BeginInit();
            this.tbRelativeVersionFile.Properties.BeginInit();
            this.tbCurrentBuild.Properties.BeginInit();
            this.tbDescription.Properties.BeginInit();
            this.tbExeName.Properties.BeginInit();
            this.bpGames.SuspendLayout();
            base.SuspendLayout();
            base.pbBottom.Size = new Size(0x346, 0x39);
            base.ttDefault.SetSuperTip(base.pbBottom, null);
            base.ttDefault.DefaultController.AutoPopDelay = 0x3e8;
            base.ttDefault.DefaultController.ToolTipLocation = ToolTipLocation.RightTop;
            this.lbGames.Anchor = AnchorStyles.Left | AnchorStyles.Bottom | AnchorStyles.Top;
            this.lbGames.BackColor = Color.Black;
            this.lbGames.BorderStyle = BorderStyle.None;
            this.lbGames.ForeColor = Color.White;
            this.lbGames.FormattingEnabled = true;
            this.lbGames.Location = new Point(11, 14);
            this.lbGames.Name = "lbGames";
            this.lbGames.Size = new Size(0xe3, 520);
            base.ttDefault.SetSuperTip(this.lbGames, null);
            this.lbGames.TabIndex = 0x1d;
            this.bpModify.Anchor = AnchorStyles.Right | AnchorStyles.Left | AnchorStyles.Bottom | AnchorStyles.Top;
            this.bpModify.Controls.Add(this.tbLongDescription);
            this.bpModify.Controls.Add(this.gpgLabel11);
            this.bpModify.Controls.Add(this.tbInstallDirectory);
            this.bpModify.Controls.Add(this.gpgLabel10);
            this.bpModify.Controls.Add(this.tbPatchUrl);
            this.bpModify.Controls.Add(this.gpgLabel9);
            this.bpModify.Controls.Add(this.tbPatcherAppUrl);
            this.bpModify.Controls.Add(this.gpgLabel8);
            this.bpModify.Controls.Add(this.tbIconLabel);
            this.bpModify.Controls.Add(this.gpgLabel7);
            this.bpModify.Controls.Add(this.tbForcedCommandLineArgs);
            this.bpModify.Controls.Add(this.gpgLabel6);
            this.bpModify.Controls.Add(this.tbRelativeAppDirectory);
            this.bpModify.Controls.Add(this.gpgLabel5);
            this.bpModify.Controls.Add(this.tbRelativeVersionFile);
            this.bpModify.Controls.Add(this.gpgLabel4);
            this.bpModify.Controls.Add(this.tbCurrentBuild);
            this.bpModify.Controls.Add(this.gpgLabel1);
            this.bpModify.Controls.Add(this.gpgLabel2);
            this.bpModify.Controls.Add(this.tbDescription);
            this.bpModify.Controls.Add(this.tbExeName);
            this.bpModify.Controls.Add(this.gpgLabel3);
            this.bpModify.Enabled = false;
            this.bpModify.GPGBorderStyle = GPGBorderStyle.Web;
            this.bpModify.Location = new Point(270, 0x6c);
            this.bpModify.Name = "bpModify";
            this.bpModify.Size = new Size(0x260, 0x239);
            base.ttDefault.SetSuperTip(this.bpModify, null);
            this.bpModify.TabIndex = 0x1f;
            this.bpModify.Text = "gpgBorderPanel1";
            this.tbLongDescription.Anchor = AnchorStyles.Right | AnchorStyles.Left | AnchorStyles.Bottom | AnchorStyles.Top;
            this.tbLongDescription.BorderColor = Color.White;
            this.tbLongDescription.Location = new Point(0x10, 0x1c3);
            this.tbLongDescription.Name = "tbLongDescription";
            this.tbLongDescription.Properties.Appearance.BackColor = Color.Black;
            this.tbLongDescription.Properties.Appearance.BorderColor = Color.FromArgb(0x52, 0x83, 190);
            this.tbLongDescription.Properties.Appearance.ForeColor = Color.White;
            this.tbLongDescription.Properties.Appearance.Options.UseBackColor = true;
            this.tbLongDescription.Properties.Appearance.Options.UseBorderColor = true;
            this.tbLongDescription.Properties.Appearance.Options.UseForeColor = true;
            this.tbLongDescription.Properties.AppearanceFocused.BackColor = Color.FromArgb(0x10, 0x21, 0x4f);
            this.tbLongDescription.Properties.AppearanceFocused.BackColor2 = Color.FromArgb(0, 0, 0);
            this.tbLongDescription.Properties.AppearanceFocused.BorderColor = Color.FromArgb(0xbb, 0xc9, 0xe2);
            this.tbLongDescription.Properties.AppearanceFocused.GradientMode = LinearGradientMode.ForwardDiagonal;
            this.tbLongDescription.Properties.AppearanceFocused.Options.UseBackColor = true;
            this.tbLongDescription.Properties.AppearanceFocused.Options.UseBorderColor = true;
            this.tbLongDescription.Properties.BorderStyle = BorderStyles.Simple;
            this.tbLongDescription.Properties.LookAndFeel.SkinName = "London Liquid Sky";
            this.tbLongDescription.Properties.LookAndFeel.UseDefaultLookAndFeel = false;
            this.tbLongDescription.Size = new Size(0x245, 0x59);
            this.tbLongDescription.TabIndex = 30;
            this.gpgLabel11.AutoGrowDirection = GrowDirections.None;
            this.gpgLabel11.AutoSize = true;
            this.gpgLabel11.AutoStyle = true;
            this.gpgLabel11.Font = new Font("Arial", 9.75f);
            this.gpgLabel11.ForeColor = Color.White;
            this.gpgLabel11.IgnoreMouseWheel = false;
            this.gpgLabel11.IsStyled = false;
            this.gpgLabel11.Location = new Point(13, 0x1b0);
            this.gpgLabel11.Name = "gpgLabel11";
            this.gpgLabel11.Size = new Size(0xb2, 0x10);
            base.ttDefault.SetSuperTip(this.gpgLabel11, null);
            this.gpgLabel11.TabIndex = 0x1d;
            this.gpgLabel11.Text = "Game Description in the vault";
            this.gpgLabel11.TextStyle = TextStyles.Default;
            this.tbInstallDirectory.Anchor = AnchorStyles.Right | AnchorStyles.Left | AnchorStyles.Top;
            this.tbInstallDirectory.Location = new Point(0x10, 0x199);
            this.tbInstallDirectory.Name = "tbInstallDirectory";
            this.tbInstallDirectory.Properties.Appearance.BackColor = Color.Black;
            this.tbInstallDirectory.Properties.Appearance.BorderColor = Color.FromArgb(0x52, 0x83, 190);
            this.tbInstallDirectory.Properties.Appearance.ForeColor = Color.White;
            this.tbInstallDirectory.Properties.Appearance.Options.UseBackColor = true;
            this.tbInstallDirectory.Properties.Appearance.Options.UseBorderColor = true;
            this.tbInstallDirectory.Properties.Appearance.Options.UseForeColor = true;
            this.tbInstallDirectory.Properties.AppearanceFocused.BackColor = Color.FromArgb(0x10, 0x21, 0x4f);
            this.tbInstallDirectory.Properties.AppearanceFocused.BackColor2 = Color.FromArgb(0, 0, 0);
            this.tbInstallDirectory.Properties.AppearanceFocused.BorderColor = Color.FromArgb(0xbb, 0xc9, 0xe2);
            this.tbInstallDirectory.Properties.AppearanceFocused.GradientMode = LinearGradientMode.ForwardDiagonal;
            this.tbInstallDirectory.Properties.AppearanceFocused.Options.UseBackColor = true;
            this.tbInstallDirectory.Properties.AppearanceFocused.Options.UseBorderColor = true;
            this.tbInstallDirectory.Properties.BorderStyle = BorderStyles.Simple;
            this.tbInstallDirectory.Properties.LookAndFeel.SkinName = "London Liquid Sky";
            this.tbInstallDirectory.Properties.LookAndFeel.UseDefaultLookAndFeel = false;
            this.tbInstallDirectory.Size = new Size(0x245, 20);
            this.tbInstallDirectory.TabIndex = 0x1c;
            this.gpgLabel10.AutoGrowDirection = GrowDirections.None;
            this.gpgLabel10.AutoSize = true;
            this.gpgLabel10.AutoStyle = true;
            this.gpgLabel10.Font = new Font("Arial", 9.75f);
            this.gpgLabel10.ForeColor = Color.White;
            this.gpgLabel10.IgnoreMouseWheel = false;
            this.gpgLabel10.IsStyled = false;
            this.gpgLabel10.Location = new Point(13, 390);
            this.gpgLabel10.Name = "gpgLabel10";
            this.gpgLabel10.Size = new Size(0x23e, 0x10);
            base.ttDefault.SetSuperTip(this.gpgLabel10, null);
            this.gpgLabel10.TabIndex = 0x1b;
            this.gpgLabel10.Text = @"Suggested Installation Directory under Program Files (example: Gas Powered Games\Test Game)";
            this.gpgLabel10.TextStyle = TextStyles.Default;
            this.tbPatchUrl.Anchor = AnchorStyles.Right | AnchorStyles.Left | AnchorStyles.Top;
            this.tbPatchUrl.Location = new Point(0x10, 0x16f);
            this.tbPatchUrl.Name = "tbPatchUrl";
            this.tbPatchUrl.Properties.Appearance.BackColor = Color.Black;
            this.tbPatchUrl.Properties.Appearance.BorderColor = Color.FromArgb(0x52, 0x83, 190);
            this.tbPatchUrl.Properties.Appearance.ForeColor = Color.White;
            this.tbPatchUrl.Properties.Appearance.Options.UseBackColor = true;
            this.tbPatchUrl.Properties.Appearance.Options.UseBorderColor = true;
            this.tbPatchUrl.Properties.Appearance.Options.UseForeColor = true;
            this.tbPatchUrl.Properties.AppearanceFocused.BackColor = Color.FromArgb(0x10, 0x21, 0x4f);
            this.tbPatchUrl.Properties.AppearanceFocused.BackColor2 = Color.FromArgb(0, 0, 0);
            this.tbPatchUrl.Properties.AppearanceFocused.BorderColor = Color.FromArgb(0xbb, 0xc9, 0xe2);
            this.tbPatchUrl.Properties.AppearanceFocused.GradientMode = LinearGradientMode.ForwardDiagonal;
            this.tbPatchUrl.Properties.AppearanceFocused.Options.UseBackColor = true;
            this.tbPatchUrl.Properties.AppearanceFocused.Options.UseBorderColor = true;
            this.tbPatchUrl.Properties.BorderStyle = BorderStyles.Simple;
            this.tbPatchUrl.Properties.LookAndFeel.SkinName = "London Liquid Sky";
            this.tbPatchUrl.Properties.LookAndFeel.UseDefaultLookAndFeel = false;
            this.tbPatchUrl.Size = new Size(0x245, 20);
            this.tbPatchUrl.TabIndex = 0x1a;
            this.gpgLabel9.AutoGrowDirection = GrowDirections.None;
            this.gpgLabel9.AutoSize = true;
            this.gpgLabel9.AutoStyle = true;
            this.gpgLabel9.Font = new Font("Arial", 9.75f);
            this.gpgLabel9.ForeColor = Color.White;
            this.gpgLabel9.IgnoreMouseWheel = false;
            this.gpgLabel9.IsStyled = false;
            this.gpgLabel9.Location = new Point(13, 0x15c);
            this.gpgLabel9.Name = "gpgLabel9";
            this.gpgLabel9.Size = new Size(0x83, 0x10);
            base.ttDefault.SetSuperTip(this.gpgLabel9, null);
            this.gpgLabel9.TabIndex = 0x19;
            this.gpgLabel9.Text = "Patch Download URL";
            this.gpgLabel9.TextStyle = TextStyles.Default;
            this.tbPatcherAppUrl.Anchor = AnchorStyles.Right | AnchorStyles.Left | AnchorStyles.Top;
            this.tbPatcherAppUrl.Location = new Point(0x10, 0x145);
            this.tbPatcherAppUrl.Name = "tbPatcherAppUrl";
            this.tbPatcherAppUrl.Properties.Appearance.BackColor = Color.Black;
            this.tbPatcherAppUrl.Properties.Appearance.BorderColor = Color.FromArgb(0x52, 0x83, 190);
            this.tbPatcherAppUrl.Properties.Appearance.ForeColor = Color.White;
            this.tbPatcherAppUrl.Properties.Appearance.Options.UseBackColor = true;
            this.tbPatcherAppUrl.Properties.Appearance.Options.UseBorderColor = true;
            this.tbPatcherAppUrl.Properties.Appearance.Options.UseForeColor = true;
            this.tbPatcherAppUrl.Properties.AppearanceFocused.BackColor = Color.FromArgb(0x10, 0x21, 0x4f);
            this.tbPatcherAppUrl.Properties.AppearanceFocused.BackColor2 = Color.FromArgb(0, 0, 0);
            this.tbPatcherAppUrl.Properties.AppearanceFocused.BorderColor = Color.FromArgb(0xbb, 0xc9, 0xe2);
            this.tbPatcherAppUrl.Properties.AppearanceFocused.GradientMode = LinearGradientMode.ForwardDiagonal;
            this.tbPatcherAppUrl.Properties.AppearanceFocused.Options.UseBackColor = true;
            this.tbPatcherAppUrl.Properties.AppearanceFocused.Options.UseBorderColor = true;
            this.tbPatcherAppUrl.Properties.BorderStyle = BorderStyles.Simple;
            this.tbPatcherAppUrl.Properties.LookAndFeel.SkinName = "London Liquid Sky";
            this.tbPatcherAppUrl.Properties.LookAndFeel.UseDefaultLookAndFeel = false;
            this.tbPatcherAppUrl.Size = new Size(0x245, 20);
            this.tbPatcherAppUrl.TabIndex = 0x18;
            this.gpgLabel8.AutoGrowDirection = GrowDirections.None;
            this.gpgLabel8.AutoSize = true;
            this.gpgLabel8.AutoStyle = true;
            this.gpgLabel8.Font = new Font("Arial", 9.75f);
            this.gpgLabel8.ForeColor = Color.White;
            this.gpgLabel8.IgnoreMouseWheel = false;
            this.gpgLabel8.IsStyled = false;
            this.gpgLabel8.Location = new Point(13, 0x132);
            this.gpgLabel8.Name = "gpgLabel8";
            this.gpgLabel8.Size = new Size(150, 0x10);
            base.ttDefault.SetSuperTip(this.gpgLabel8, null);
            this.gpgLabel8.TabIndex = 0x17;
            this.gpgLabel8.Text = "Patcher Application URL";
            this.gpgLabel8.TextStyle = TextStyles.Default;
            this.tbIconLabel.Anchor = AnchorStyles.Right | AnchorStyles.Left | AnchorStyles.Top;
            this.tbIconLabel.Location = new Point(0x10, 0x11b);
            this.tbIconLabel.Name = "tbIconLabel";
            this.tbIconLabel.Properties.Appearance.BackColor = Color.Black;
            this.tbIconLabel.Properties.Appearance.BorderColor = Color.FromArgb(0x52, 0x83, 190);
            this.tbIconLabel.Properties.Appearance.ForeColor = Color.White;
            this.tbIconLabel.Properties.Appearance.Options.UseBackColor = true;
            this.tbIconLabel.Properties.Appearance.Options.UseBorderColor = true;
            this.tbIconLabel.Properties.Appearance.Options.UseForeColor = true;
            this.tbIconLabel.Properties.AppearanceFocused.BackColor = Color.FromArgb(0x10, 0x21, 0x4f);
            this.tbIconLabel.Properties.AppearanceFocused.BackColor2 = Color.FromArgb(0, 0, 0);
            this.tbIconLabel.Properties.AppearanceFocused.BorderColor = Color.FromArgb(0xbb, 0xc9, 0xe2);
            this.tbIconLabel.Properties.AppearanceFocused.GradientMode = LinearGradientMode.ForwardDiagonal;
            this.tbIconLabel.Properties.AppearanceFocused.Options.UseBackColor = true;
            this.tbIconLabel.Properties.AppearanceFocused.Options.UseBorderColor = true;
            this.tbIconLabel.Properties.BorderStyle = BorderStyles.Simple;
            this.tbIconLabel.Properties.LookAndFeel.SkinName = "London Liquid Sky";
            this.tbIconLabel.Properties.LookAndFeel.UseDefaultLookAndFeel = false;
            this.tbIconLabel.Size = new Size(0x245, 20);
            this.tbIconLabel.TabIndex = 0x16;
            this.gpgLabel7.AutoGrowDirection = GrowDirections.None;
            this.gpgLabel7.AutoSize = true;
            this.gpgLabel7.AutoStyle = true;
            this.gpgLabel7.Font = new Font("Arial", 9.75f);
            this.gpgLabel7.ForeColor = Color.White;
            this.gpgLabel7.IgnoreMouseWheel = false;
            this.gpgLabel7.IsStyled = false;
            this.gpgLabel7.Location = new Point(13, 0x108);
            this.gpgLabel7.Name = "gpgLabel7";
            this.gpgLabel7.Size = new Size(0xf5, 0x10);
            base.ttDefault.SetSuperTip(this.gpgLabel7, null);
            this.gpgLabel7.TabIndex = 0x15;
            this.gpgLabel7.Text = "Icon Label (Appears on top of game icon)";
            this.gpgLabel7.TextStyle = TextStyles.Default;
            this.tbForcedCommandLineArgs.Anchor = AnchorStyles.Right | AnchorStyles.Left | AnchorStyles.Top;
            this.tbForcedCommandLineArgs.Location = new Point(0x10, 0xf1);
            this.tbForcedCommandLineArgs.Name = "tbForcedCommandLineArgs";
            this.tbForcedCommandLineArgs.Properties.Appearance.BackColor = Color.Black;
            this.tbForcedCommandLineArgs.Properties.Appearance.BorderColor = Color.FromArgb(0x52, 0x83, 190);
            this.tbForcedCommandLineArgs.Properties.Appearance.ForeColor = Color.White;
            this.tbForcedCommandLineArgs.Properties.Appearance.Options.UseBackColor = true;
            this.tbForcedCommandLineArgs.Properties.Appearance.Options.UseBorderColor = true;
            this.tbForcedCommandLineArgs.Properties.Appearance.Options.UseForeColor = true;
            this.tbForcedCommandLineArgs.Properties.AppearanceFocused.BackColor = Color.FromArgb(0x10, 0x21, 0x4f);
            this.tbForcedCommandLineArgs.Properties.AppearanceFocused.BackColor2 = Color.FromArgb(0, 0, 0);
            this.tbForcedCommandLineArgs.Properties.AppearanceFocused.BorderColor = Color.FromArgb(0xbb, 0xc9, 0xe2);
            this.tbForcedCommandLineArgs.Properties.AppearanceFocused.GradientMode = LinearGradientMode.ForwardDiagonal;
            this.tbForcedCommandLineArgs.Properties.AppearanceFocused.Options.UseBackColor = true;
            this.tbForcedCommandLineArgs.Properties.AppearanceFocused.Options.UseBorderColor = true;
            this.tbForcedCommandLineArgs.Properties.BorderStyle = BorderStyles.Simple;
            this.tbForcedCommandLineArgs.Properties.LookAndFeel.SkinName = "London Liquid Sky";
            this.tbForcedCommandLineArgs.Properties.LookAndFeel.UseDefaultLookAndFeel = false;
            this.tbForcedCommandLineArgs.Size = new Size(0x245, 20);
            this.tbForcedCommandLineArgs.TabIndex = 20;
            this.gpgLabel6.AutoGrowDirection = GrowDirections.None;
            this.gpgLabel6.AutoSize = true;
            this.gpgLabel6.AutoStyle = true;
            this.gpgLabel6.Font = new Font("Arial", 9.75f);
            this.gpgLabel6.ForeColor = Color.White;
            this.gpgLabel6.IgnoreMouseWheel = false;
            this.gpgLabel6.IsStyled = false;
            this.gpgLabel6.Location = new Point(13, 0xde);
            this.gpgLabel6.Name = "gpgLabel6";
            this.gpgLabel6.Size = new Size(0x119, 0x10);
            base.ttDefault.SetSuperTip(this.gpgLabel6, null);
            this.gpgLabel6.TabIndex = 0x13;
            this.gpgLabel6.Text = "Force Command Line Arguments on All Users";
            this.gpgLabel6.TextStyle = TextStyles.Default;
            this.tbRelativeAppDirectory.Anchor = AnchorStyles.Right | AnchorStyles.Left | AnchorStyles.Top;
            this.tbRelativeAppDirectory.Location = new Point(0x10, 0xc7);
            this.tbRelativeAppDirectory.Name = "tbRelativeAppDirectory";
            this.tbRelativeAppDirectory.Properties.Appearance.BackColor = Color.Black;
            this.tbRelativeAppDirectory.Properties.Appearance.BorderColor = Color.FromArgb(0x52, 0x83, 190);
            this.tbRelativeAppDirectory.Properties.Appearance.ForeColor = Color.White;
            this.tbRelativeAppDirectory.Properties.Appearance.Options.UseBackColor = true;
            this.tbRelativeAppDirectory.Properties.Appearance.Options.UseBorderColor = true;
            this.tbRelativeAppDirectory.Properties.Appearance.Options.UseForeColor = true;
            this.tbRelativeAppDirectory.Properties.AppearanceFocused.BackColor = Color.FromArgb(0x10, 0x21, 0x4f);
            this.tbRelativeAppDirectory.Properties.AppearanceFocused.BackColor2 = Color.FromArgb(0, 0, 0);
            this.tbRelativeAppDirectory.Properties.AppearanceFocused.BorderColor = Color.FromArgb(0xbb, 0xc9, 0xe2);
            this.tbRelativeAppDirectory.Properties.AppearanceFocused.GradientMode = LinearGradientMode.ForwardDiagonal;
            this.tbRelativeAppDirectory.Properties.AppearanceFocused.Options.UseBackColor = true;
            this.tbRelativeAppDirectory.Properties.AppearanceFocused.Options.UseBorderColor = true;
            this.tbRelativeAppDirectory.Properties.BorderStyle = BorderStyles.Simple;
            this.tbRelativeAppDirectory.Properties.LookAndFeel.SkinName = "London Liquid Sky";
            this.tbRelativeAppDirectory.Properties.LookAndFeel.UseDefaultLookAndFeel = false;
            this.tbRelativeAppDirectory.Size = new Size(0x245, 20);
            this.tbRelativeAppDirectory.TabIndex = 0x12;
            this.gpgLabel5.AutoGrowDirection = GrowDirections.None;
            this.gpgLabel5.AutoSize = true;
            this.gpgLabel5.AutoStyle = true;
            this.gpgLabel5.Font = new Font("Arial", 9.75f);
            this.gpgLabel5.ForeColor = Color.White;
            this.gpgLabel5.IgnoreMouseWheel = false;
            this.gpgLabel5.IsStyled = false;
            this.gpgLabel5.Location = new Point(13, 180);
            this.gpgLabel5.Name = "gpgLabel5";
            this.gpgLabel5.Size = new Size(0xb1, 0x10);
            base.ttDefault.SetSuperTip(this.gpgLabel5, null);
            this.gpgLabel5.TabIndex = 0x11;
            this.gpgLabel5.Text = "Relative Application Directory";
            this.gpgLabel5.TextStyle = TextStyles.Default;
            this.tbRelativeVersionFile.Anchor = AnchorStyles.Right | AnchorStyles.Left | AnchorStyles.Top;
            this.tbRelativeVersionFile.Location = new Point(0x10, 0x9d);
            this.tbRelativeVersionFile.Name = "tbRelativeVersionFile";
            this.tbRelativeVersionFile.Properties.Appearance.BackColor = Color.Black;
            this.tbRelativeVersionFile.Properties.Appearance.BorderColor = Color.FromArgb(0x52, 0x83, 190);
            this.tbRelativeVersionFile.Properties.Appearance.ForeColor = Color.White;
            this.tbRelativeVersionFile.Properties.Appearance.Options.UseBackColor = true;
            this.tbRelativeVersionFile.Properties.Appearance.Options.UseBorderColor = true;
            this.tbRelativeVersionFile.Properties.Appearance.Options.UseForeColor = true;
            this.tbRelativeVersionFile.Properties.AppearanceFocused.BackColor = Color.FromArgb(0x10, 0x21, 0x4f);
            this.tbRelativeVersionFile.Properties.AppearanceFocused.BackColor2 = Color.FromArgb(0, 0, 0);
            this.tbRelativeVersionFile.Properties.AppearanceFocused.BorderColor = Color.FromArgb(0xbb, 0xc9, 0xe2);
            this.tbRelativeVersionFile.Properties.AppearanceFocused.GradientMode = LinearGradientMode.ForwardDiagonal;
            this.tbRelativeVersionFile.Properties.AppearanceFocused.Options.UseBackColor = true;
            this.tbRelativeVersionFile.Properties.AppearanceFocused.Options.UseBorderColor = true;
            this.tbRelativeVersionFile.Properties.BorderStyle = BorderStyles.Simple;
            this.tbRelativeVersionFile.Properties.LookAndFeel.SkinName = "London Liquid Sky";
            this.tbRelativeVersionFile.Properties.LookAndFeel.UseDefaultLookAndFeel = false;
            this.tbRelativeVersionFile.Size = new Size(0x245, 20);
            this.tbRelativeVersionFile.TabIndex = 0x10;
            this.gpgLabel4.AutoGrowDirection = GrowDirections.None;
            this.gpgLabel4.AutoSize = true;
            this.gpgLabel4.AutoStyle = true;
            this.gpgLabel4.Font = new Font("Arial", 9.75f);
            this.gpgLabel4.ForeColor = Color.White;
            this.gpgLabel4.IgnoreMouseWheel = false;
            this.gpgLabel4.IsStyled = false;
            this.gpgLabel4.Location = new Point(13, 0x8a);
            this.gpgLabel4.Name = "gpgLabel4";
            this.gpgLabel4.Size = new Size(0x7e, 0x10);
            base.ttDefault.SetSuperTip(this.gpgLabel4, null);
            this.gpgLabel4.TabIndex = 15;
            this.gpgLabel4.Text = "Relative Version File";
            this.gpgLabel4.TextStyle = TextStyles.Default;
            this.tbCurrentBuild.Anchor = AnchorStyles.Right | AnchorStyles.Left | AnchorStyles.Top;
            this.tbCurrentBuild.Location = new Point(0x10, 0x73);
            this.tbCurrentBuild.Name = "tbCurrentBuild";
            this.tbCurrentBuild.Properties.Appearance.BackColor = Color.Black;
            this.tbCurrentBuild.Properties.Appearance.BorderColor = Color.FromArgb(0x52, 0x83, 190);
            this.tbCurrentBuild.Properties.Appearance.ForeColor = Color.White;
            this.tbCurrentBuild.Properties.Appearance.Options.UseBackColor = true;
            this.tbCurrentBuild.Properties.Appearance.Options.UseBorderColor = true;
            this.tbCurrentBuild.Properties.Appearance.Options.UseForeColor = true;
            this.tbCurrentBuild.Properties.AppearanceFocused.BackColor = Color.FromArgb(0x10, 0x21, 0x4f);
            this.tbCurrentBuild.Properties.AppearanceFocused.BackColor2 = Color.FromArgb(0, 0, 0);
            this.tbCurrentBuild.Properties.AppearanceFocused.BorderColor = Color.FromArgb(0xbb, 0xc9, 0xe2);
            this.tbCurrentBuild.Properties.AppearanceFocused.GradientMode = LinearGradientMode.ForwardDiagonal;
            this.tbCurrentBuild.Properties.AppearanceFocused.Options.UseBackColor = true;
            this.tbCurrentBuild.Properties.AppearanceFocused.Options.UseBorderColor = true;
            this.tbCurrentBuild.Properties.BorderStyle = BorderStyles.Simple;
            this.tbCurrentBuild.Properties.LookAndFeel.SkinName = "London Liquid Sky";
            this.tbCurrentBuild.Properties.LookAndFeel.UseDefaultLookAndFeel = false;
            this.tbCurrentBuild.Size = new Size(0x245, 20);
            this.tbCurrentBuild.TabIndex = 14;
            this.gpgLabel1.AutoGrowDirection = GrowDirections.None;
            this.gpgLabel1.AutoSize = true;
            this.gpgLabel1.AutoStyle = true;
            this.gpgLabel1.Font = new Font("Arial", 9.75f);
            this.gpgLabel1.ForeColor = Color.White;
            this.gpgLabel1.IgnoreMouseWheel = false;
            this.gpgLabel1.IsStyled = false;
            this.gpgLabel1.Location = new Point(13, 0x60);
            this.gpgLabel1.Name = "gpgLabel1";
            this.gpgLabel1.Size = new Size(0x62, 0x10);
            base.ttDefault.SetSuperTip(this.gpgLabel1, null);
            this.gpgLabel1.TabIndex = 13;
            this.gpgLabel1.Text = "Current Version";
            this.gpgLabel1.TextStyle = TextStyles.Default;
            this.gpgLabel2.AutoGrowDirection = GrowDirections.None;
            this.gpgLabel2.AutoSize = true;
            this.gpgLabel2.AutoStyle = true;
            this.gpgLabel2.Font = new Font("Arial", 9.75f);
            this.gpgLabel2.ForeColor = Color.White;
            this.gpgLabel2.IgnoreMouseWheel = false;
            this.gpgLabel2.IsStyled = false;
            this.gpgLabel2.Location = new Point(13, 12);
            this.gpgLabel2.Name = "gpgLabel2";
            this.gpgLabel2.Size = new Size(0x70, 0x10);
            base.ttDefault.SetSuperTip(this.gpgLabel2, null);
            this.gpgLabel2.TabIndex = 9;
            this.gpgLabel2.Text = "Game Description";
            this.gpgLabel2.TextStyle = TextStyles.Default;
            this.tbDescription.Anchor = AnchorStyles.Right | AnchorStyles.Left | AnchorStyles.Top;
            this.tbDescription.Location = new Point(0x10, 0x1f);
            this.tbDescription.Name = "tbDescription";
            this.tbDescription.Properties.Appearance.BackColor = Color.Black;
            this.tbDescription.Properties.Appearance.BorderColor = Color.FromArgb(0x52, 0x83, 190);
            this.tbDescription.Properties.Appearance.ForeColor = Color.White;
            this.tbDescription.Properties.Appearance.Options.UseBackColor = true;
            this.tbDescription.Properties.Appearance.Options.UseBorderColor = true;
            this.tbDescription.Properties.Appearance.Options.UseForeColor = true;
            this.tbDescription.Properties.AppearanceFocused.BackColor = Color.FromArgb(0x10, 0x21, 0x4f);
            this.tbDescription.Properties.AppearanceFocused.BackColor2 = Color.FromArgb(0, 0, 0);
            this.tbDescription.Properties.AppearanceFocused.BorderColor = Color.FromArgb(0xbb, 0xc9, 0xe2);
            this.tbDescription.Properties.AppearanceFocused.GradientMode = LinearGradientMode.ForwardDiagonal;
            this.tbDescription.Properties.AppearanceFocused.Options.UseBackColor = true;
            this.tbDescription.Properties.AppearanceFocused.Options.UseBorderColor = true;
            this.tbDescription.Properties.BorderStyle = BorderStyles.Simple;
            this.tbDescription.Properties.LookAndFeel.SkinName = "London Liquid Sky";
            this.tbDescription.Properties.LookAndFeel.UseDefaultLookAndFeel = false;
            this.tbDescription.Size = new Size(0x245, 20);
            this.tbDescription.TabIndex = 10;
            this.tbExeName.Anchor = AnchorStyles.Right | AnchorStyles.Left | AnchorStyles.Top;
            this.tbExeName.Location = new Point(0x10, 0x49);
            this.tbExeName.Name = "tbExeName";
            this.tbExeName.Properties.Appearance.BackColor = Color.Black;
            this.tbExeName.Properties.Appearance.BorderColor = Color.FromArgb(0x52, 0x83, 190);
            this.tbExeName.Properties.Appearance.ForeColor = Color.White;
            this.tbExeName.Properties.Appearance.Options.UseBackColor = true;
            this.tbExeName.Properties.Appearance.Options.UseBorderColor = true;
            this.tbExeName.Properties.Appearance.Options.UseForeColor = true;
            this.tbExeName.Properties.AppearanceFocused.BackColor = Color.FromArgb(0x10, 0x21, 0x4f);
            this.tbExeName.Properties.AppearanceFocused.BackColor2 = Color.FromArgb(0, 0, 0);
            this.tbExeName.Properties.AppearanceFocused.BorderColor = Color.FromArgb(0xbb, 0xc9, 0xe2);
            this.tbExeName.Properties.AppearanceFocused.GradientMode = LinearGradientMode.ForwardDiagonal;
            this.tbExeName.Properties.AppearanceFocused.Options.UseBackColor = true;
            this.tbExeName.Properties.AppearanceFocused.Options.UseBorderColor = true;
            this.tbExeName.Properties.BorderStyle = BorderStyles.Simple;
            this.tbExeName.Properties.LookAndFeel.SkinName = "London Liquid Sky";
            this.tbExeName.Properties.LookAndFeel.UseDefaultLookAndFeel = false;
            this.tbExeName.Size = new Size(0x245, 20);
            this.tbExeName.TabIndex = 12;
            this.gpgLabel3.AutoGrowDirection = GrowDirections.None;
            this.gpgLabel3.AutoSize = true;
            this.gpgLabel3.AutoStyle = true;
            this.gpgLabel3.Font = new Font("Arial", 9.75f);
            this.gpgLabel3.ForeColor = Color.White;
            this.gpgLabel3.IgnoreMouseWheel = false;
            this.gpgLabel3.IsStyled = false;
            this.gpgLabel3.Location = new Point(13, 0x36);
            this.gpgLabel3.Name = "gpgLabel3";
            this.gpgLabel3.Size = new Size(0x45, 0x10);
            base.ttDefault.SetSuperTip(this.gpgLabel3, null);
            this.gpgLabel3.TabIndex = 11;
            this.gpgLabel3.Text = "Exe Name";
            this.gpgLabel3.TextStyle = TextStyles.Default;
            this.sbAdd.Anchor = AnchorStyles.Right | AnchorStyles.Bottom;
            this.sbAdd.AutoStyle = true;
            this.sbAdd.BackColor = Color.Black;
            this.sbAdd.ButtonState = 0;
            this.sbAdd.DialogResult = DialogResult.OK;
            this.sbAdd.DisabledForecolor = Color.Gray;
            this.sbAdd.DrawColor = Color.White;
            this.sbAdd.DrawEdges = true;
            this.sbAdd.FocusColor = Color.Yellow;
            this.sbAdd.Font = new Font("Verdana", 8f, FontStyle.Bold);
            this.sbAdd.ForeColor = Color.White;
            this.sbAdd.HorizontalScalingMode = ScalingModes.Tile;
            this.sbAdd.IsStyled = true;
            this.sbAdd.Location = new Point(0x169, 0x2ab);
            this.sbAdd.Name = "sbAdd";
            this.sbAdd.Size = new Size(0x7f, 0x1c);
            this.sbAdd.SkinBasePath = @"Controls\Button\Round Edge";
            base.ttDefault.SetSuperTip(this.sbAdd, null);
            this.sbAdd.TabIndex = 30;
            this.sbAdd.TabStop = true;
            this.sbAdd.Text = "Add New Game";
            this.sbAdd.TextAlign = ContentAlignment.MiddleCenter;
            this.sbAdd.TextPadding = new Padding(0);
            this.sbModify.Anchor = AnchorStyles.Right | AnchorStyles.Bottom;
            this.sbModify.AutoStyle = true;
            this.sbModify.BackColor = Color.Black;
            this.sbModify.ButtonState = 0;
            this.sbModify.DialogResult = DialogResult.OK;
            this.sbModify.DisabledForecolor = Color.Gray;
            this.sbModify.DrawColor = Color.White;
            this.sbModify.DrawEdges = true;
            this.sbModify.FocusColor = Color.Yellow;
            this.sbModify.Font = new Font("Verdana", 8f, FontStyle.Bold);
            this.sbModify.ForeColor = Color.White;
            this.sbModify.HorizontalScalingMode = ScalingModes.Tile;
            this.sbModify.IsStyled = true;
            this.sbModify.Location = new Point(0x273, 0x2ab);
            this.sbModify.Name = "sbModify";
            this.sbModify.Size = new Size(0x7f, 0x1c);
            this.sbModify.SkinBasePath = @"Controls\Button\Round Edge";
            base.ttDefault.SetSuperTip(this.sbModify, null);
            this.sbModify.TabIndex = 0x20;
            this.sbModify.TabStop = true;
            this.sbModify.Text = "Modify";
            this.sbModify.TextAlign = ContentAlignment.MiddleCenter;
            this.sbModify.TextPadding = new Padding(0);
            this.sbCancel.Anchor = AnchorStyles.Right | AnchorStyles.Bottom;
            this.sbCancel.AutoStyle = true;
            this.sbCancel.BackColor = Color.Black;
            this.sbCancel.ButtonState = 0;
            this.sbCancel.DialogResult = DialogResult.OK;
            this.sbCancel.DisabledForecolor = Color.Gray;
            this.sbCancel.DrawColor = Color.White;
            this.sbCancel.DrawEdges = true;
            this.sbCancel.Enabled = false;
            this.sbCancel.FocusColor = Color.Yellow;
            this.sbCancel.Font = new Font("Verdana", 8f, FontStyle.Bold);
            this.sbCancel.ForeColor = Color.White;
            this.sbCancel.HorizontalScalingMode = ScalingModes.Tile;
            this.sbCancel.IsStyled = true;
            this.sbCancel.Location = new Point(760, 0x2ab);
            this.sbCancel.Name = "sbCancel";
            this.sbCancel.Size = new Size(0x7f, 0x1c);
            this.sbCancel.SkinBasePath = @"Controls\Button\Round Edge";
            base.ttDefault.SetSuperTip(this.sbCancel, null);
            this.sbCancel.TabIndex = 0x21;
            this.sbCancel.TabStop = true;
            this.sbCancel.Text = "Cancel";
            this.sbCancel.TextAlign = ContentAlignment.MiddleCenter;
            this.sbCancel.TextPadding = new Padding(0);
            this.sbSaveChanges.Anchor = AnchorStyles.Right | AnchorStyles.Bottom;
            this.sbSaveChanges.AutoStyle = true;
            this.sbSaveChanges.BackColor = Color.Black;
            this.sbSaveChanges.ButtonState = 0;
            this.sbSaveChanges.DialogResult = DialogResult.OK;
            this.sbSaveChanges.DisabledForecolor = Color.Gray;
            this.sbSaveChanges.DrawColor = Color.White;
            this.sbSaveChanges.DrawEdges = true;
            this.sbSaveChanges.Enabled = false;
            this.sbSaveChanges.FocusColor = Color.Yellow;
            this.sbSaveChanges.Font = new Font("Verdana", 8f, FontStyle.Bold);
            this.sbSaveChanges.ForeColor = Color.White;
            this.sbSaveChanges.HorizontalScalingMode = ScalingModes.Tile;
            this.sbSaveChanges.IsStyled = true;
            this.sbSaveChanges.Location = new Point(0x1ee, 0x2ab);
            this.sbSaveChanges.Name = "sbSaveChanges";
            this.sbSaveChanges.Size = new Size(0x7f, 0x1c);
            this.sbSaveChanges.SkinBasePath = @"Controls\Button\Round Edge";
            base.ttDefault.SetSuperTip(this.sbSaveChanges, null);
            this.sbSaveChanges.TabIndex = 0x22;
            this.sbSaveChanges.TabStop = true;
            this.sbSaveChanges.Text = "Save Changes";
            this.sbSaveChanges.TextAlign = ContentAlignment.MiddleCenter;
            this.sbSaveChanges.TextPadding = new Padding(0);
            this.bpGames.Anchor = AnchorStyles.Left | AnchorStyles.Bottom | AnchorStyles.Top;
            this.bpGames.Controls.Add(this.lbGames);
            this.bpGames.GPGBorderStyle = GPGBorderStyle.Web;
            this.bpGames.Location = new Point(12, 0x6c);
            this.bpGames.Name = "bpGames";
            this.bpGames.Size = new Size(0xfc, 0x239);
            base.ttDefault.SetSuperTip(this.bpGames, null);
            this.bpGames.TabIndex = 0x23;
            this.bpGames.Text = "gpgBorderPanel1";
            base.AutoScaleDimensions = new SizeF(7f, 13f);
            base.AutoScaleMode = AutoScaleMode.Font;
            base.ClientSize = new Size(0x381, 0x31c);
            base.Controls.Add(this.bpGames);
            base.Controls.Add(this.sbSaveChanges);
            base.Controls.Add(this.sbCancel);
            base.Controls.Add(this.sbModify);
            base.Controls.Add(this.bpModify);
            base.Controls.Add(this.sbAdd);
            this.Font = new Font("Verdana", 8f);
            base.Location = new Point(0, 0);
            base.Name = "DlgGameVersionManager";
            base.ttDefault.SetSuperTip(this, null);
            this.Text = "DlgGameVersionManager";
            base.Controls.SetChildIndex(this.sbAdd, 0);
            base.Controls.SetChildIndex(this.bpModify, 0);
            base.Controls.SetChildIndex(this.sbModify, 0);
            base.Controls.SetChildIndex(this.sbCancel, 0);
            base.Controls.SetChildIndex(this.sbSaveChanges, 0);
            base.Controls.SetChildIndex(this.bpGames, 0);
            ((ISupportInitialize) base.pbBottom).EndInit();
            this.bpModify.ResumeLayout(false);
            this.bpModify.PerformLayout();
            this.tbLongDescription.Properties.EndInit();
            this.tbInstallDirectory.Properties.EndInit();
            this.tbPatchUrl.Properties.EndInit();
            this.tbPatcherAppUrl.Properties.EndInit();
            this.tbIconLabel.Properties.EndInit();
            this.tbForcedCommandLineArgs.Properties.EndInit();
            this.tbRelativeAppDirectory.Properties.EndInit();
            this.tbRelativeVersionFile.Properties.EndInit();
            this.tbCurrentBuild.Properties.EndInit();
            this.tbDescription.Properties.EndInit();
            this.tbExeName.Properties.EndInit();
            this.bpGames.ResumeLayout(false);
            base.ResumeLayout(false);
            base.PerformLayout();
        }

        private void lbGames_Click(object sender, EventArgs e)
        {
            GameInformation selectedItem = this.lbGames.SelectedItem as GameInformation;
            if (selectedItem != null)
            {
                this.tbDescription.Text = selectedItem.GameDescription;
                this.tbExeName.Text = selectedItem.ExeName;
                this.tbCurrentBuild.Text = selectedItem.CurrentVersion;
                this.tbRelativeAppDirectory.Text = selectedItem.ApplicationDirectory;
                this.tbRelativeVersionFile.Text = selectedItem.VersionFile;
                this.tbForcedCommandLineArgs.Text = selectedItem.ForcedCommandLineArgs;
                this.tbIconLabel.Text = selectedItem.IconLabel;
                this.tbPatcherAppUrl.Text = selectedItem.PatcherAppURL;
                this.tbPatchUrl.Text = selectedItem.PatchURL;
                this.tbLongDescription.Text = selectedItem.LongDescription;
                this.tbInstallDirectory.Text = selectedItem.InstallDirectory;
            }
            else
            {
                this.tbDescription.Text = "";
                this.tbExeName.Text = "";
                this.tbCurrentBuild.Text = "";
                this.tbRelativeAppDirectory.Text = "";
                this.tbRelativeVersionFile.Text = "";
                this.tbForcedCommandLineArgs.Text = "";
                this.tbIconLabel.Text = "";
                this.tbPatcherAppUrl.Text = "";
                this.tbPatchUrl.Text = "";
                this.tbLongDescription.Text = "";
                this.tbInstallDirectory.Text = "";
            }
        }

        private void RefreshGamesList()
        {
            this.lbGames.Items.Clear();
            GameInformation.LoadGamesFromDB();
            foreach (GameInformation information in GameInformation.Games)
            {
                this.lbGames.Items.Add(information);
            }
        }

        private void sbAdd_Click(object sender, EventArgs e)
        {
            this.mAddMode = true;
            GameInformation item = new GameInformation();
            item.GameDescription = "New Game";
            item.PatcherAppURL = "http://thevault.gaspowered.com/webpatch.exe";
            item.PatchURL = "http://thevault.gaspowered.com/PatchService/Service.asmx?WSDL";
            this.lbGames.Items.Add(item);
            this.lbGames.SelectedItem = item;
            this.SetEditMode(true);
        }

        private void sbCancel_Click(object sender, EventArgs e)
        {
            this.SetEditMode(false);
            this.RefreshGamesList();
        }

        private void sbModify_Click(object sender, EventArgs e)
        {
            this.mAddMode = false;
            this.SetEditMode(true);
        }

        private void sbSaveChanges_Click(object sender, EventArgs e)
        {
            this.SetEditMode(false);
            if (this.mAddMode)
            {
                DataAccess.ExecuteQuery("Insert GPGnet Game", new object[] { this.tbDescription.Text, this.tbExeName.Text, this.tbCurrentBuild.Text, this.tbRelativeVersionFile.Text, this.tbRelativeAppDirectory.Text, this.tbForcedCommandLineArgs.Text, this.tbIconLabel.Text, this.tbPatcherAppUrl.Text, this.tbPatchUrl.Text, this.tbLongDescription.Text, this.tbInstallDirectory.Text });
            }
            else
            {
                GameInformation selectedItem = this.lbGames.SelectedItem as GameInformation;
                DataAccess.ExecuteQuery("Update GPGnet Game", new object[] { this.tbDescription.Text, this.tbExeName.Text, this.tbCurrentBuild.Text, this.tbRelativeVersionFile.Text, this.tbRelativeAppDirectory.Text, this.tbForcedCommandLineArgs.Text, this.tbIconLabel.Text, this.tbPatcherAppUrl.Text, this.tbPatchUrl.Text, this.tbLongDescription.Text, this.tbInstallDirectory.Text, selectedItem.GameID });
            }
            this.RefreshGamesList();
        }

        private void SetEditMode(bool editing)
        {
            this.sbSaveChanges.Enabled = editing;
            this.sbCancel.Enabled = editing;
            this.bpModify.Enabled = editing;
            this.bpGames.Enabled = !editing;
            this.sbModify.Enabled = !editing;
            this.sbAdd.Enabled = !editing;
        }
    }
}

