namespace GPG.Multiplayer.Quazal
{
    using System;

    public enum CustomCommands : uint
    {
        AddUser = 0x23,
        AM1 = 60,
        AutomatchAbortChallenge = 0x8d,
        AutomatchAbortDirectChallenge = 0xb5,
        AutomatchAccept = 0x13,
        AutomatchAcknowledge = 20,
        AutomatchAcknowledgeTeam = 0x8f,
        AutomatchBusy = 0x16,
        AutomatchCancelAlliance = 0x87,
        AutomatchConfirm = 0x15,
        AutomatchConfirmAlliance = 0x86,
        AutomatchConfirmChallenge = 140,
        AutomatchDecline = 0x8e,
        AutomatchDirectChallenge = 0x8b,
        AutomatchEndAlliance = 0x88,
        AutomatchLaunch = 0x17,
        AutomatchNotifyAllies = 0x84,
        AutomatchRequest = 0x12,
        AutomatchRequestAlliance = 0x85,
        AutomatchStatusMessage = 0x89,
        AutomatchTeamMembers = 0x90,
        AutomatchTeamName = 0x8a,
        Ban = 0x11,
        ChangeLocation = 0x1f,
        ChangeName = 0x24,
        ClanMemberOnline = 9,
        EmoteUnavailable = 40,
        EndPrivateMessage = 0x20,
        EnterChannel = 0x22,
        EventDisconnect = 0x1d,
        EventExit = 0x1b,
        EventOperator = 0x1c,
        FriendInvite = 12,
        GameEvent = 30,
        GameLobbyMessage = 300,
        InviteToClan = 10,
        Kick = 0x10,
        LadderChallengeAccept = 0xbf,
        LadderChallengeDecline = 0xc0,
        LadderChallengeRequest = 190,
        NetData = 0x19,
        OnlineStatus = 3,
        PingRequest = 50,
        PingResponse = 0x33,
        PlayerMessage = 0x34,
        RefreshFriends = 13,
        RemoveFriend = 14,
        RequestClanInvite = 11,
        RequestEmotes = 0x18,
        SetChatEffect = 6,
        SetStatus = 5,
        SystemEvent = 0x1a,
        SystemMessage = 1,
        TeamGame = 0x97,
        TeamGameAbort = 0xa3,
        TeamGameAcceptInvite = 0x9e,
        TeamGameDeclineInvite = 0x9f,
        TeamGameDisband = 0x9a,
        TeamGameEnd = 0xa6,
        TeamGameFull = 160,
        TeamGameInvite = 0x9d,
        TeamGameKick = 0x9b,
        TeamGameLaunch = 0x99,
        TeamGameLeave = 0x9c,
        TeamGameMap = 0xa1,
        TeamGameMember = 0x98,
        TeamGameMessage = 150,
        TeamGameStart = 0xa5,
        TeamGameStatus = 0xa2,
        TeamGameUnavailable = 0xa4,
        TournamentAcknowledgeStatus = 0xb1,
        TournamentChatmessage = 0xb2,
        TournamentChatroom = 0xaf,
        TournamentClientResult = 0xad,
        TournamentEndMatch = 0xb3,
        TournamentGameStarted = 0xae,
        TournamentLaunchGame = 170,
        TournamentRefreshData = 0xab,
        TournamentRequestStatus = 0xb0,
        TournamentReservedCmd9 = 180,
        TournamentResult = 0xac,
        Unknown = 0,
        UpdateClan = 7,
        UpdateClanMember = 8,
        UpdateSender = 2,
        UpdateUser = 0x21,
        Whisper = 15
    }
}

