namespace GPG.Multiplayer.Client.Games.SupremeCommander.tournaments
{
    using DevExpress.Utils;
    using DevExpress.XtraEditors.Controls;
    using GPG.Multiplayer.Client;
    using GPG.Multiplayer.Client.Controls;
    using GPG.Multiplayer.UI.Controls;
    using GPG.UI;
    using System;
    using System.ComponentModel;
    using System.Drawing;
    using System.Drawing.Drawing2D;
    using System.Windows.Forms;

    public class DlgSetResults : DlgBase
    {
        public SkinButton btnCustomRoom;
        private IContainer components = null;
        private GPGLabel gpgLabel1;
        private GPGLabel gpgLabel2;
        private GPGLabel gpgLabel3;
        private GPGLabel gpgLabel4;
        private GPGLabel gpgLabel5;
        private GPGLabel gpgLabel6;
        public GPGLabel lPlayer1;
        public GPGLabel lPlayer2;
        public GPGTextBox tbPlayer1Draws;
        public GPGTextBox tbPlayer1Losses;
        public GPGTextBox tbPlayer1Wins;
        public GPGTextBox tbPlayer2Draws;
        public GPGTextBox tbPlayer2Losses;
        public GPGTextBox tbPlayer2Wins;

        public DlgSetResults()
        {
            this.InitializeComponent();
        }

        private void btnCustomRoom_Click(object sender, EventArgs e)
        {
            base.DialogResult = DialogResult.OK;
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.tbPlayer1Wins = new GPGTextBox();
            this.lPlayer1 = new GPGLabel();
            this.lPlayer2 = new GPGLabel();
            this.gpgLabel1 = new GPGLabel();
            this.gpgLabel2 = new GPGLabel();
            this.tbPlayer1Losses = new GPGTextBox();
            this.gpgLabel3 = new GPGLabel();
            this.tbPlayer1Draws = new GPGTextBox();
            this.gpgLabel4 = new GPGLabel();
            this.tbPlayer2Draws = new GPGTextBox();
            this.gpgLabel5 = new GPGLabel();
            this.tbPlayer2Losses = new GPGTextBox();
            this.gpgLabel6 = new GPGLabel();
            this.tbPlayer2Wins = new GPGTextBox();
            this.btnCustomRoom = new SkinButton();
            ((ISupportInitialize) base.pbBottom).BeginInit();
            this.tbPlayer1Wins.Properties.BeginInit();
            this.tbPlayer1Losses.Properties.BeginInit();
            this.tbPlayer1Draws.Properties.BeginInit();
            this.tbPlayer2Draws.Properties.BeginInit();
            this.tbPlayer2Losses.Properties.BeginInit();
            this.tbPlayer2Wins.Properties.BeginInit();
            base.SuspendLayout();
            base.pbBottom.Size = new Size(0xe4, 0x39);
            base.ttDefault.SetSuperTip(base.pbBottom, null);
            base.ttDefault.DefaultController.AutoPopDelay = 0x3e8;
            base.ttDefault.DefaultController.ToolTipLocation = ToolTipLocation.RightTop;
            this.tbPlayer1Wins.Location = new Point(0x3b, 0x7a);
            this.tbPlayer1Wins.Name = "tbPlayer1Wins";
            this.tbPlayer1Wins.Properties.Appearance.BackColor = Color.Black;
            this.tbPlayer1Wins.Properties.Appearance.BorderColor = Color.FromArgb(0x52, 0x83, 190);
            this.tbPlayer1Wins.Properties.Appearance.ForeColor = Color.White;
            this.tbPlayer1Wins.Properties.Appearance.Options.UseBackColor = true;
            this.tbPlayer1Wins.Properties.Appearance.Options.UseBorderColor = true;
            this.tbPlayer1Wins.Properties.Appearance.Options.UseForeColor = true;
            this.tbPlayer1Wins.Properties.AppearanceFocused.BackColor = Color.FromArgb(0x10, 0x21, 0x4f);
            this.tbPlayer1Wins.Properties.AppearanceFocused.BackColor2 = Color.FromArgb(0, 0, 0);
            this.tbPlayer1Wins.Properties.AppearanceFocused.BorderColor = Color.FromArgb(0xbb, 0xc9, 0xe2);
            this.tbPlayer1Wins.Properties.AppearanceFocused.GradientMode = LinearGradientMode.ForwardDiagonal;
            this.tbPlayer1Wins.Properties.AppearanceFocused.Options.UseBackColor = true;
            this.tbPlayer1Wins.Properties.AppearanceFocused.Options.UseBorderColor = true;
            this.tbPlayer1Wins.Properties.BorderStyle = BorderStyles.Simple;
            this.tbPlayer1Wins.Properties.LookAndFeel.SkinName = "London Liquid Sky";
            this.tbPlayer1Wins.Properties.LookAndFeel.UseDefaultLookAndFeel = false;
            this.tbPlayer1Wins.Size = new Size(0x31, 20);
            this.tbPlayer1Wins.TabIndex = 7;
            this.lPlayer1.AutoGrowDirection = GrowDirections.None;
            this.lPlayer1.AutoSize = true;
            this.lPlayer1.AutoStyle = true;
            this.lPlayer1.Font = new Font("Arial", 9.75f);
            this.lPlayer1.ForeColor = Color.White;
            this.lPlayer1.IgnoreMouseWheel = false;
            this.lPlayer1.IsStyled = false;
            this.lPlayer1.Location = new Point(0x19, 0x67);
            this.lPlayer1.Name = "lPlayer1";
            this.lPlayer1.Size = new Size(0x34, 0x10);
            base.ttDefault.SetSuperTip(this.lPlayer1, null);
            this.lPlayer1.TabIndex = 8;
            this.lPlayer1.Text = "Player1";
            this.lPlayer1.TextStyle = TextStyles.Default;
            this.lPlayer2.AutoGrowDirection = GrowDirections.None;
            this.lPlayer2.AutoSize = true;
            this.lPlayer2.AutoStyle = true;
            this.lPlayer2.Font = new Font("Arial", 9.75f);
            this.lPlayer2.ForeColor = Color.White;
            this.lPlayer2.IgnoreMouseWheel = false;
            this.lPlayer2.IsStyled = false;
            this.lPlayer2.Location = new Point(0x1d, 0x9c);
            this.lPlayer2.Name = "lPlayer2";
            this.lPlayer2.Size = new Size(0x34, 0x10);
            base.ttDefault.SetSuperTip(this.lPlayer2, null);
            this.lPlayer2.TabIndex = 9;
            this.lPlayer2.Text = "Player2";
            this.lPlayer2.TextStyle = TextStyles.Default;
            this.gpgLabel1.AutoGrowDirection = GrowDirections.None;
            this.gpgLabel1.AutoSize = true;
            this.gpgLabel1.AutoStyle = true;
            this.gpgLabel1.Font = new Font("Arial", 9.75f);
            this.gpgLabel1.ForeColor = Color.White;
            this.gpgLabel1.IgnoreMouseWheel = false;
            this.gpgLabel1.IsStyled = false;
            this.gpgLabel1.Location = new Point(0x26, 0x7a);
            this.gpgLabel1.Name = "gpgLabel1";
            this.gpgLabel1.Size = new Size(0x15, 0x10);
            base.ttDefault.SetSuperTip(this.gpgLabel1, null);
            this.gpgLabel1.TabIndex = 10;
            this.gpgLabel1.Text = "W";
            this.gpgLabel1.TextStyle = TextStyles.Default;
            this.gpgLabel2.AutoGrowDirection = GrowDirections.None;
            this.gpgLabel2.AutoSize = true;
            this.gpgLabel2.AutoStyle = true;
            this.gpgLabel2.Font = new Font("Arial", 9.75f);
            this.gpgLabel2.ForeColor = Color.White;
            this.gpgLabel2.IgnoreMouseWheel = false;
            this.gpgLabel2.IsStyled = false;
            this.gpgLabel2.Location = new Point(0x74, 0x7a);
            this.gpgLabel2.Name = "gpgLabel2";
            this.gpgLabel2.Size = new Size(15, 0x10);
            base.ttDefault.SetSuperTip(this.gpgLabel2, null);
            this.gpgLabel2.TabIndex = 12;
            this.gpgLabel2.Text = "L";
            this.gpgLabel2.TextStyle = TextStyles.Default;
            this.tbPlayer1Losses.Location = new Point(0x85, 0x7a);
            this.tbPlayer1Losses.Name = "tbPlayer1Losses";
            this.tbPlayer1Losses.Properties.Appearance.BackColor = Color.Black;
            this.tbPlayer1Losses.Properties.Appearance.BorderColor = Color.FromArgb(0x52, 0x83, 190);
            this.tbPlayer1Losses.Properties.Appearance.ForeColor = Color.White;
            this.tbPlayer1Losses.Properties.Appearance.Options.UseBackColor = true;
            this.tbPlayer1Losses.Properties.Appearance.Options.UseBorderColor = true;
            this.tbPlayer1Losses.Properties.Appearance.Options.UseForeColor = true;
            this.tbPlayer1Losses.Properties.AppearanceFocused.BackColor = Color.FromArgb(0x10, 0x21, 0x4f);
            this.tbPlayer1Losses.Properties.AppearanceFocused.BackColor2 = Color.FromArgb(0, 0, 0);
            this.tbPlayer1Losses.Properties.AppearanceFocused.BorderColor = Color.FromArgb(0xbb, 0xc9, 0xe2);
            this.tbPlayer1Losses.Properties.AppearanceFocused.GradientMode = LinearGradientMode.ForwardDiagonal;
            this.tbPlayer1Losses.Properties.AppearanceFocused.Options.UseBackColor = true;
            this.tbPlayer1Losses.Properties.AppearanceFocused.Options.UseBorderColor = true;
            this.tbPlayer1Losses.Properties.BorderStyle = BorderStyles.Simple;
            this.tbPlayer1Losses.Properties.LookAndFeel.SkinName = "London Liquid Sky";
            this.tbPlayer1Losses.Properties.LookAndFeel.UseDefaultLookAndFeel = false;
            this.tbPlayer1Losses.Size = new Size(0x31, 20);
            this.tbPlayer1Losses.TabIndex = 11;
            this.gpgLabel3.AutoGrowDirection = GrowDirections.None;
            this.gpgLabel3.AutoSize = true;
            this.gpgLabel3.AutoStyle = true;
            this.gpgLabel3.Font = new Font("Arial", 9.75f);
            this.gpgLabel3.ForeColor = Color.White;
            this.gpgLabel3.IgnoreMouseWheel = false;
            this.gpgLabel3.IsStyled = false;
            this.gpgLabel3.Location = new Point(0xbd, 0x7a);
            this.gpgLabel3.Name = "gpgLabel3";
            this.gpgLabel3.Size = new Size(0x11, 0x10);
            base.ttDefault.SetSuperTip(this.gpgLabel3, null);
            this.gpgLabel3.TabIndex = 14;
            this.gpgLabel3.Text = "D";
            this.gpgLabel3.TextStyle = TextStyles.Default;
            this.tbPlayer1Draws.Location = new Point(0xd0, 0x7a);
            this.tbPlayer1Draws.Name = "tbPlayer1Draws";
            this.tbPlayer1Draws.Properties.Appearance.BackColor = Color.Black;
            this.tbPlayer1Draws.Properties.Appearance.BorderColor = Color.FromArgb(0x52, 0x83, 190);
            this.tbPlayer1Draws.Properties.Appearance.ForeColor = Color.White;
            this.tbPlayer1Draws.Properties.Appearance.Options.UseBackColor = true;
            this.tbPlayer1Draws.Properties.Appearance.Options.UseBorderColor = true;
            this.tbPlayer1Draws.Properties.Appearance.Options.UseForeColor = true;
            this.tbPlayer1Draws.Properties.AppearanceFocused.BackColor = Color.FromArgb(0x10, 0x21, 0x4f);
            this.tbPlayer1Draws.Properties.AppearanceFocused.BackColor2 = Color.FromArgb(0, 0, 0);
            this.tbPlayer1Draws.Properties.AppearanceFocused.BorderColor = Color.FromArgb(0xbb, 0xc9, 0xe2);
            this.tbPlayer1Draws.Properties.AppearanceFocused.GradientMode = LinearGradientMode.ForwardDiagonal;
            this.tbPlayer1Draws.Properties.AppearanceFocused.Options.UseBackColor = true;
            this.tbPlayer1Draws.Properties.AppearanceFocused.Options.UseBorderColor = true;
            this.tbPlayer1Draws.Properties.BorderStyle = BorderStyles.Simple;
            this.tbPlayer1Draws.Properties.LookAndFeel.SkinName = "London Liquid Sky";
            this.tbPlayer1Draws.Properties.LookAndFeel.UseDefaultLookAndFeel = false;
            this.tbPlayer1Draws.Size = new Size(0x31, 20);
            this.tbPlayer1Draws.TabIndex = 13;
            this.gpgLabel4.AutoGrowDirection = GrowDirections.None;
            this.gpgLabel4.AutoSize = true;
            this.gpgLabel4.AutoStyle = true;
            this.gpgLabel4.Font = new Font("Arial", 9.75f);
            this.gpgLabel4.ForeColor = Color.White;
            this.gpgLabel4.IgnoreMouseWheel = false;
            this.gpgLabel4.IsStyled = false;
            this.gpgLabel4.Location = new Point(0xbd, 0xb0);
            this.gpgLabel4.Name = "gpgLabel4";
            this.gpgLabel4.Size = new Size(0x11, 0x10);
            base.ttDefault.SetSuperTip(this.gpgLabel4, null);
            this.gpgLabel4.TabIndex = 20;
            this.gpgLabel4.Text = "D";
            this.gpgLabel4.TextStyle = TextStyles.Default;
            this.tbPlayer2Draws.Location = new Point(0xd0, 0xb0);
            this.tbPlayer2Draws.Name = "tbPlayer2Draws";
            this.tbPlayer2Draws.Properties.Appearance.BackColor = Color.Black;
            this.tbPlayer2Draws.Properties.Appearance.BorderColor = Color.FromArgb(0x52, 0x83, 190);
            this.tbPlayer2Draws.Properties.Appearance.ForeColor = Color.White;
            this.tbPlayer2Draws.Properties.Appearance.Options.UseBackColor = true;
            this.tbPlayer2Draws.Properties.Appearance.Options.UseBorderColor = true;
            this.tbPlayer2Draws.Properties.Appearance.Options.UseForeColor = true;
            this.tbPlayer2Draws.Properties.AppearanceFocused.BackColor = Color.FromArgb(0x10, 0x21, 0x4f);
            this.tbPlayer2Draws.Properties.AppearanceFocused.BackColor2 = Color.FromArgb(0, 0, 0);
            this.tbPlayer2Draws.Properties.AppearanceFocused.BorderColor = Color.FromArgb(0xbb, 0xc9, 0xe2);
            this.tbPlayer2Draws.Properties.AppearanceFocused.GradientMode = LinearGradientMode.ForwardDiagonal;
            this.tbPlayer2Draws.Properties.AppearanceFocused.Options.UseBackColor = true;
            this.tbPlayer2Draws.Properties.AppearanceFocused.Options.UseBorderColor = true;
            this.tbPlayer2Draws.Properties.BorderStyle = BorderStyles.Simple;
            this.tbPlayer2Draws.Properties.LookAndFeel.SkinName = "London Liquid Sky";
            this.tbPlayer2Draws.Properties.LookAndFeel.UseDefaultLookAndFeel = false;
            this.tbPlayer2Draws.Size = new Size(0x31, 20);
            this.tbPlayer2Draws.TabIndex = 0x13;
            this.gpgLabel5.AutoGrowDirection = GrowDirections.None;
            this.gpgLabel5.AutoSize = true;
            this.gpgLabel5.AutoStyle = true;
            this.gpgLabel5.Font = new Font("Arial", 9.75f);
            this.gpgLabel5.ForeColor = Color.White;
            this.gpgLabel5.IgnoreMouseWheel = false;
            this.gpgLabel5.IsStyled = false;
            this.gpgLabel5.Location = new Point(0x74, 0xb0);
            this.gpgLabel5.Name = "gpgLabel5";
            this.gpgLabel5.Size = new Size(15, 0x10);
            base.ttDefault.SetSuperTip(this.gpgLabel5, null);
            this.gpgLabel5.TabIndex = 0x12;
            this.gpgLabel5.Text = "L";
            this.gpgLabel5.TextStyle = TextStyles.Default;
            this.tbPlayer2Losses.Location = new Point(0x85, 0xb0);
            this.tbPlayer2Losses.Name = "tbPlayer2Losses";
            this.tbPlayer2Losses.Properties.Appearance.BackColor = Color.Black;
            this.tbPlayer2Losses.Properties.Appearance.BorderColor = Color.FromArgb(0x52, 0x83, 190);
            this.tbPlayer2Losses.Properties.Appearance.ForeColor = Color.White;
            this.tbPlayer2Losses.Properties.Appearance.Options.UseBackColor = true;
            this.tbPlayer2Losses.Properties.Appearance.Options.UseBorderColor = true;
            this.tbPlayer2Losses.Properties.Appearance.Options.UseForeColor = true;
            this.tbPlayer2Losses.Properties.AppearanceFocused.BackColor = Color.FromArgb(0x10, 0x21, 0x4f);
            this.tbPlayer2Losses.Properties.AppearanceFocused.BackColor2 = Color.FromArgb(0, 0, 0);
            this.tbPlayer2Losses.Properties.AppearanceFocused.BorderColor = Color.FromArgb(0xbb, 0xc9, 0xe2);
            this.tbPlayer2Losses.Properties.AppearanceFocused.GradientMode = LinearGradientMode.ForwardDiagonal;
            this.tbPlayer2Losses.Properties.AppearanceFocused.Options.UseBackColor = true;
            this.tbPlayer2Losses.Properties.AppearanceFocused.Options.UseBorderColor = true;
            this.tbPlayer2Losses.Properties.BorderStyle = BorderStyles.Simple;
            this.tbPlayer2Losses.Properties.LookAndFeel.SkinName = "London Liquid Sky";
            this.tbPlayer2Losses.Properties.LookAndFeel.UseDefaultLookAndFeel = false;
            this.tbPlayer2Losses.Size = new Size(0x31, 20);
            this.tbPlayer2Losses.TabIndex = 0x11;
            this.gpgLabel6.AutoGrowDirection = GrowDirections.None;
            this.gpgLabel6.AutoSize = true;
            this.gpgLabel6.AutoStyle = true;
            this.gpgLabel6.Font = new Font("Arial", 9.75f);
            this.gpgLabel6.ForeColor = Color.White;
            this.gpgLabel6.IgnoreMouseWheel = false;
            this.gpgLabel6.IsStyled = false;
            this.gpgLabel6.Location = new Point(0x26, 0xb0);
            this.gpgLabel6.Name = "gpgLabel6";
            this.gpgLabel6.Size = new Size(0x15, 0x10);
            base.ttDefault.SetSuperTip(this.gpgLabel6, null);
            this.gpgLabel6.TabIndex = 0x10;
            this.gpgLabel6.Text = "W";
            this.gpgLabel6.TextStyle = TextStyles.Default;
            this.tbPlayer2Wins.Location = new Point(0x3b, 0xb0);
            this.tbPlayer2Wins.Name = "tbPlayer2Wins";
            this.tbPlayer2Wins.Properties.Appearance.BackColor = Color.Black;
            this.tbPlayer2Wins.Properties.Appearance.BorderColor = Color.FromArgb(0x52, 0x83, 190);
            this.tbPlayer2Wins.Properties.Appearance.ForeColor = Color.White;
            this.tbPlayer2Wins.Properties.Appearance.Options.UseBackColor = true;
            this.tbPlayer2Wins.Properties.Appearance.Options.UseBorderColor = true;
            this.tbPlayer2Wins.Properties.Appearance.Options.UseForeColor = true;
            this.tbPlayer2Wins.Properties.AppearanceFocused.BackColor = Color.FromArgb(0x10, 0x21, 0x4f);
            this.tbPlayer2Wins.Properties.AppearanceFocused.BackColor2 = Color.FromArgb(0, 0, 0);
            this.tbPlayer2Wins.Properties.AppearanceFocused.BorderColor = Color.FromArgb(0xbb, 0xc9, 0xe2);
            this.tbPlayer2Wins.Properties.AppearanceFocused.GradientMode = LinearGradientMode.ForwardDiagonal;
            this.tbPlayer2Wins.Properties.AppearanceFocused.Options.UseBackColor = true;
            this.tbPlayer2Wins.Properties.AppearanceFocused.Options.UseBorderColor = true;
            this.tbPlayer2Wins.Properties.BorderStyle = BorderStyles.Simple;
            this.tbPlayer2Wins.Properties.LookAndFeel.SkinName = "London Liquid Sky";
            this.tbPlayer2Wins.Properties.LookAndFeel.UseDefaultLookAndFeel = false;
            this.tbPlayer2Wins.Size = new Size(0x31, 20);
            this.tbPlayer2Wins.TabIndex = 15;
            this.btnCustomRoom.Anchor = AnchorStyles.Right | AnchorStyles.Bottom;
            this.btnCustomRoom.AutoStyle = true;
            this.btnCustomRoom.BackColor = Color.Black;
            this.btnCustomRoom.ButtonState = 0;
            this.btnCustomRoom.DialogResult = DialogResult.None;
            this.btnCustomRoom.DisabledForecolor = Color.Gray;
            this.btnCustomRoom.DrawColor = Color.White;
            this.btnCustomRoom.DrawEdges = true;
            this.btnCustomRoom.FocusColor = Color.Yellow;
            this.btnCustomRoom.Font = new Font("Verdana", 8f, FontStyle.Bold);
            this.btnCustomRoom.ForeColor = Color.White;
            this.btnCustomRoom.HorizontalScalingMode = ScalingModes.Tile;
            this.btnCustomRoom.IsStyled = true;
            this.btnCustomRoom.Location = new Point(0x7f, 0xca);
            this.btnCustomRoom.Name = "btnCustomRoom";
            this.btnCustomRoom.Size = new Size(130, 0x16);
            this.btnCustomRoom.SkinBasePath = @"Controls\Button\Round Edge";
            base.ttDefault.SetSuperTip(this.btnCustomRoom, null);
            this.btnCustomRoom.TabIndex = 0x23;
            this.btnCustomRoom.TabStop = true;
            this.btnCustomRoom.Text = "<LOC>OK";
            this.btnCustomRoom.TextAlign = ContentAlignment.MiddleCenter;
            this.btnCustomRoom.TextPadding = new Padding(0);
            this.btnCustomRoom.Click += new EventHandler(this.btnCustomRoom_Click);
            base.AutoScaleDimensions = new SizeF(7f, 13f);
            base.AutoScaleMode = AutoScaleMode.Font;
            base.ClientSize = new Size(0x11f, 0x116);
            base.Controls.Add(this.btnCustomRoom);
            base.Controls.Add(this.gpgLabel4);
            base.Controls.Add(this.tbPlayer2Draws);
            base.Controls.Add(this.gpgLabel5);
            base.Controls.Add(this.tbPlayer2Losses);
            base.Controls.Add(this.gpgLabel6);
            base.Controls.Add(this.tbPlayer2Wins);
            base.Controls.Add(this.gpgLabel3);
            base.Controls.Add(this.tbPlayer1Draws);
            base.Controls.Add(this.gpgLabel2);
            base.Controls.Add(this.tbPlayer1Losses);
            base.Controls.Add(this.gpgLabel1);
            base.Controls.Add(this.lPlayer2);
            base.Controls.Add(this.lPlayer1);
            base.Controls.Add(this.tbPlayer1Wins);
            this.Font = new Font("Verdana", 8f);
            base.Location = new Point(0, 0);
            this.MaximumSize = new Size(0x11f, 0x116);
            this.MinimumSize = new Size(0x11f, 0x116);
            base.Name = "DlgSetResults";
            base.ttDefault.SetSuperTip(this, null);
            this.Text = "DlgSetResults";
            base.Controls.SetChildIndex(this.tbPlayer1Wins, 0);
            base.Controls.SetChildIndex(this.lPlayer1, 0);
            base.Controls.SetChildIndex(this.lPlayer2, 0);
            base.Controls.SetChildIndex(this.gpgLabel1, 0);
            base.Controls.SetChildIndex(this.tbPlayer1Losses, 0);
            base.Controls.SetChildIndex(this.gpgLabel2, 0);
            base.Controls.SetChildIndex(this.tbPlayer1Draws, 0);
            base.Controls.SetChildIndex(this.gpgLabel3, 0);
            base.Controls.SetChildIndex(this.tbPlayer2Wins, 0);
            base.Controls.SetChildIndex(this.gpgLabel6, 0);
            base.Controls.SetChildIndex(this.tbPlayer2Losses, 0);
            base.Controls.SetChildIndex(this.gpgLabel5, 0);
            base.Controls.SetChildIndex(this.tbPlayer2Draws, 0);
            base.Controls.SetChildIndex(this.gpgLabel4, 0);
            base.Controls.SetChildIndex(this.btnCustomRoom, 0);
            ((ISupportInitialize) base.pbBottom).EndInit();
            this.tbPlayer1Wins.Properties.EndInit();
            this.tbPlayer1Losses.Properties.EndInit();
            this.tbPlayer1Draws.Properties.EndInit();
            this.tbPlayer2Draws.Properties.EndInit();
            this.tbPlayer2Losses.Properties.EndInit();
            this.tbPlayer2Wins.Properties.EndInit();
            base.ResumeLayout(false);
            base.PerformLayout();
        }
    }
}

